-- Generated by Mocodo 4.3.2

CREATE TABLE ASSURE (
  PRIMARY KEY (id_assure),
  id_assure      VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  prenom         VARCHAR(42),
  date_naissance VARCHAR(42),
  email          VARCHAR(42),
  mdp_assure     VARCHAR(42),
  telephone      VARCHAR(42)
);

CREATE TABLE ASSUREUR (
  PRIMARY KEY (id_assureur),
  id_assureur  VARCHAR(42) NOT NULL,
  nom          VARCHAR(42),
  prenom       VARCHAR(42),
  email        VARCHAR(42),
  telephone    VARCHAR(42),
  mot_de_passe VARCHAR(42),
  societe      VARCHAR(42),
  id_assure    VARCHAR(42) NOT NULL
);

CREATE TABLE BIEN (
  PRIMARY KEY (id_bien),
  id_bien         VARCHAR(42) NOT NULL,
  nom_bien        VARCHAR(42),
  description     VARCHAR(42),
  categorie       VARCHAR(42),
  date_achat      VARCHAR(42),
  prix_achat      VARCHAR(42),
  etat            VARCHAR(42),
  valeur_actuelle VARCHAR(42)
);

CREATE TABLE IMPACTE (
  PRIMARY KEY (id_bien, id_sinistre),
  id_bien      VARCHAR(42) NOT NULL,
  id_sinistre  VARCHAR(42) NOT NULL,
  degat_estime VARCHAR(42)
);

CREATE TABLE JUSTIFICATIF (
  PRIMARY KEY (id_justificatif),
  id_justificatif   VARCHAR(42) NOT NULL,
  type_justificatif VARCHAR(42),
  chemin_fichier    VARCHAR(42),
  date_ajout        VARCHAR(42),
  id_bien           VARCHAR(42) NOT NULL
);

CREATE TABLE JUSTIFIE (
  PRIMARY KEY (id_logement, id_justificatif),
  id_logement     VARCHAR(42) NOT NULL,
  id_justificatif VARCHAR(42) NOT NULL
);

CREATE TABLE LOGEMENT (
  PRIMARY KEY (id_logement),
  id_logement   VARCHAR(42) NOT NULL,
  adresse       VARCHAR(42),
  type_logement VARCHAR(42),
  surface       VARCHAR(42),
  description   VARCHAR(42),
  id_assureur   VARCHAR(42) NOT NULL,
  id_assure     VARCHAR(42) NOT NULL,
  date_debut    VARCHAR(42),
  id_piece      VARCHAR(42) NOT NULL,
  UNIQUE (id_assureur)
);

CREATE TABLE PIECE (
  PRIMARY KEY (id_piece),
  id_piece   VARCHAR(42) NOT NULL,
  nom_piece  VARCHAR(42),
  type_piece VARCHAR(42),
  surface    VARCHAR(42),
  etage      VARCHAR(42),
  id_bien    VARCHAR(42) NOT NULL
);

CREATE TABLE POSSEDE (
  PRIMARY KEY (id_assure, id_logement),
  id_assure   VARCHAR(42) NOT NULL,
  id_logement VARCHAR(42) NOT NULL
);

CREATE TABLE SINISTRE (
  PRIMARY KEY (id_sinistre),
  id_sinistre     VARCHAR(42) NOT NULL,
  date_sinistre   VARCHAR(42),
  type_sinistre   VARCHAR(42),
  description     VARCHAR(42),
  numero_sinistre VARCHAR(42)
);

ALTER TABLE ASSUREUR ADD FOREIGN KEY (id_assure) REFERENCES ASSURE (id_assure);

ALTER TABLE IMPACTE ADD FOREIGN KEY (id_sinistre) REFERENCES SINISTRE (id_sinistre);
ALTER TABLE IMPACTE ADD FOREIGN KEY (id_bien) REFERENCES BIEN (id_bien);

ALTER TABLE JUSTIFICATIF ADD FOREIGN KEY (id_bien) REFERENCES BIEN (id_bien);

ALTER TABLE JUSTIFIE ADD FOREIGN KEY (id_justificatif) REFERENCES JUSTIFICATIF (id_justificatif);
ALTER TABLE JUSTIFIE ADD FOREIGN KEY (id_logement) REFERENCES LOGEMENT (id_logement);

ALTER TABLE LOGEMENT ADD FOREIGN KEY (id_piece) REFERENCES PIECE (id_piece);
ALTER TABLE LOGEMENT ADD FOREIGN KEY (id_assure) REFERENCES ASSURE (id_assure);
ALTER TABLE LOGEMENT ADD FOREIGN KEY (id_assureur) REFERENCES ASSUREUR (id_assureur);

ALTER TABLE PIECE ADD FOREIGN KEY (id_bien) REFERENCES BIEN (id_bien);

ALTER TABLE POSSEDE ADD FOREIGN KEY (id_logement) REFERENCES LOGEMENT (id_logement);
ALTER TABLE POSSEDE ADD FOREIGN KEY (id_assure) REFERENCES ASSURE (id_assure);
